services:
  - type: web
    name: bp-app
    runtime: node
    repo: https://github.com/Trevodorax/esgi_render_blueprint_4AL1
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-db
          property: connectionString

databases:
  - name: bp-db
    plan: free
    region: frankfurt
